// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Packing.Infrastructure.Persistence;

#nullable disable

namespace Packing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PackingDbContext))]
    [Migration("20241109130216_OrderItem")]
    partial class OrderItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Packing.Domain.Box.Box", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("BoxId");

                    b.HasKey("Id");

                    b.ToTable("Boxes", (string)null);
                });

            modelBuilder.Entity("Packing.Domain.Order.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("OrderId");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Packing.Domain.Box.Box", b =>
                {
                    b.OwnsOne("Packing.Domain.Box.ValueObjects.BoxOrder", "Order", b1 =>
                        {
                            b1.Property<Guid>("BoxId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("OrderId")
                                .HasColumnType("TEXT");

                            b1.HasKey("BoxId");

                            b1.ToTable("Boxes");

                            b1.WithOwner()
                                .HasForeignKey("BoxId");
                        });

                    b.Navigation("Order")
                        .IsRequired();
                });

            modelBuilder.Entity("Packing.Domain.Order.Order", b =>
                {
                    b.OwnsOne("Packing.Domain.Order.ValueObjects.OrderPackaged", "Packaged", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsPackaged")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime?>("PackagedAt")
                                .HasColumnType("TEXT");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsMany("Packing.Domain.Order.OrderItem.OrderItem", "OrderItems", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT")
                                .HasColumnName("OrderId");

                            b1.Property<Guid?>("OrderItemId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("OrderItemId");

                            b1.ToTable("OrderItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");

                            b1.OwnsOne("Packing.Domain.Order.OrderItem.ValueObjects.OrderProduct", "Product", b2 =>
                                {
                                    b2.Property<Guid>("OrderItemId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Amount")
                                        .HasColumnType("INTEGER");

                                    b2.Property<Guid>("GoodsId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("OrderItemId");

                                    b2.ToTable("OrderItems");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderItemId");
                                });

                            b1.Navigation("Product")
                                .IsRequired();
                        });

                    b.Navigation("OrderItems");

                    b.Navigation("Packaged")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
