// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Packing.Infrastructure.Persistence;

#nullable disable

namespace Packing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PackingDbContext))]
    [Migration("20241101154711_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Packing.Domain.Box.Box", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("BoxId");

                    b.HasKey("Id");

                    b.ToTable("Boxes", (string)null);
                });

            modelBuilder.Entity("Packing.Domain.Order.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("OrderId");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Packing.Domain.Box.Box", b =>
                {
                    b.OwnsOne("Packing.Domain.Box.ValueObjects.BoxOrder", "Order", b1 =>
                        {
                            b1.Property<Guid>("BoxId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("OrderId")
                                .HasColumnType("TEXT");

                            b1.HasKey("BoxId");

                            b1.ToTable("Boxes");

                            b1.WithOwner()
                                .HasForeignKey("BoxId");
                        });

                    b.Navigation("Order")
                        .IsRequired();
                });

            modelBuilder.Entity("Packing.Domain.Order.Order", b =>
                {
                    b.OwnsOne("Packing.Domain.Order.ValueObjects.OrderPackaged", "Packaged", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsPackaged")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime?>("PackagedAt")
                                .HasColumnType("TEXT");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Packaged")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
